# Python

Python is a high-level, interpreted, object-oriented, and multi-purpose programming language. 

# Why Python?

- Relevant (https://www.tiobe.com/tiobe-index/)
- Simple, scalable, versatile (https://www.monterail.com/blog/five-reasons-to-choose-python-for-finance-and-fintech)
- NumPy + Pandas + SciPy = Powerful!
- Multi-purpose language 
- Large community and easier query resolution

# Understanding The Environment

In [149]:
100*12.5/5

250.0

In [150]:
a = 100*12.5/5

In [151]:
# Comment type 1
'Comment type 2'
"Comment type 3"

""" Commments (doc string)
dadasdas
asdada
"""

print("xyz")

xyz


# Numerical Operations

In [152]:
# Assigning values to variables 'x' and 'y'
x = 2
y = 5
x,y

(2, 5)

In [153]:
# Python is a case sensitive language (X != x)
A = 17
a = 15
print(A,a)

17 15


In [154]:
# Addition
x+y

7

In [155]:
# Division
y/x

2.5

In [156]:
# Quotient
y//x

2

In [157]:
# Remainder
y%x

1

In [158]:
# Power
x**y

32

In [159]:
# Variables can be anything (like below) 
mfe_class_of_2023 = 2022 # no spaces allowed
#print(mfe_class_of_2023)
print(type(mfe_class_of_2023)) # what is the type? and what is integer class?

<class 'int'>


# Data Types

Class, Object, Attribute, and Method differentiate Python from R (or an object oriented language from a functional language).

A class provides a template for building data (the object) and functionality together. 

An object is an instance/creation of the class. 

A class has attributes and methods/functions. We access them by writing the command "object.attribute" or "object.function".

**Example** - consider a car to be a class. We have 3 types of cars - Toyota (White, Gas), Tesla (Black, Electric), and BMW (Grey, Hybrid). The three cars Toyota, Tesla & BMW are the objects of this class (cars). The attributes are it's color and it's power source (car specific). Methods/functions can be move forward or open door or honk.

- **Class :** Cars
- **Objects :** Toyota, Tesla, and BMW
- **Attribute :** Color, engine type
- **Function :** Go forward, reverse, honk, etc.

### Arithmetic Data Types

In [160]:
# Type tells us the variable type inside the brackets
x = 10
type(x)

int

In [161]:
# variable x can take any value - integer, boolean, string, complex numbers
x = 2
y = 2
type(x == y)

bool

In [162]:
# Checking if one variable is lesser or greater than other
print(x>y)

False


In [163]:
# Checking if two variables are different 
print(x!=y)

False


In [164]:
# Gives us the attributes and functions of x (in class int)
# Calling these functions using the object.function command
x = 5
y = 5
#dir(x)
#x.__add__(2)
#x+2

In [165]:
# Each variable points to the location of object
print(id(x),id(y),id(x)==id(y)) # unique ID for object x points to
# In C++, x and y are given a unique ID even if they contain the same data 
# This is what makes python dynamically typed (variables can refer to any type of object)
hex(id(x)) # the memory location of the object in your CPU!

140717438964672 140717438964672 True


'0x7ffb54f693c0'

### String Data Type

In [166]:
x = "MFE Class of 2023"
type(x)

str

In [167]:
x = "A B C D E"
#dir(x) # Shows us what we can do with a string
#x.lower() # converts to lower case
x.split() # One of the function of x, gives us a split string covered in []
#print(type(x.split()))

['A', 'B', 'C', 'D', 'E']

In [168]:
# We can also split a string around a specific object, in this case "."
x = " N.Djokovic is the G.O.A.T."
x.split(".")

[' N', 'Djokovic is the G', 'O', 'A', 'T', '']

# Data Structures

Data structures are a collection of related data. There are 4 built in data structures in Python - List, Tuple, Dictionary, and Set. 

### List

In [169]:
# A list always starts and ends with the square brackets []
int_list = [10,20,30] # (Python index always starts from 0) and elements are at index 0,1,2
#print(type(int_list))
int_list[0] # How would you do this in R?
#int_list

10

In [170]:
# List can also be created using the list function
list((1,2,3))

[1, 2, 3]

In [171]:
# Understanding the object and it's attributes
dir(int_list)
#int_list

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [172]:
# A list can store other lists and any data type (no restrictions)
mix_list = [[1,2,3],"MFE Class of 2020",3.14,5+4j,True]
mix_list

[[1, 2, 3], 'MFE Class of 2020', 3.14, (5+4j), True]

In [173]:
# Method 1 of adding a variable to the end of a list
mix_list.append('Hello World')
mix_list

[[1, 2, 3], 'MFE Class of 2020', 3.14, (5+4j), True, 'Hello World']

In [174]:
# Alternate way to add items to a list
mix_list+['abc123']

[[1, 2, 3], 'MFE Class of 2020', 3.14, (5+4j), True, 'Hello World', 'abc123']

In [175]:
# Something very interesting happens when you try to print(list.append())
print(mix_list.append('Hello World'))
mix_list = mix_list+['abc123']

None


In [176]:
# Method 2 of adding a variable to a list (the more preferred way)
mix_list = [[1,2,3],"MFE Class of 2020",3.14,5+4j,True]
mix_list.insert(5,'Hello World') # synatax is insert(index,variable)
mix_list

[[1, 2, 3], 'MFE Class of 2020', 3.14, (5+4j), True, 'Hello World']

In [177]:
# Printing the length of a list
print(mix_list.__len__())
len(mix_list)

6


6

In [178]:
# Removing an item from list
int_list = [1,2,2,3,4,5]
int_list.remove(2) # inpace function, 
int_list

[1, 2, 3, 4, 5]

In [179]:
int_list[1]

2

In [180]:
# Another way to remove an item from list
del int_list[1]
int_list

[1, 3, 4, 5]

In [181]:
# Referencing items in a list
int_list = [10,11,12,13,14]
int_list[0]

10

In [182]:
# Indexing (an explicit example)
"""
list11 = [1 ,  2 ,  3,  4]
index1 = [0 ,  1 ,  2,  3]
index2 = [-4, -3 , -2, -1]
"""
list11 = [1,2,3,4]

In [183]:
int_list

[10, 11, 12, 13, 14]

In [184]:
int_list[-1]

14

In [185]:
int_list[-3:-1]

[12, 13]

In [186]:
# Renaming item in a list
int_list[0] = 100
int_list

[100, 11, 12, 13, 14]

In [187]:
# Memory allocation (very important)
list1 = [1,2,3,4,5]
list2 = list1.copy()
list2[0] = 100
list2[1] = 500
list1

[1, 2, 3, 4, 5]

In [188]:
# Easy work around
list2 = list1.copy()

In [189]:
# Assigning multiple variables to same object 
a = [1,2]
b = a
print(a,b)

#a.append(3)
#print(a,b)

[1, 2] [1, 2]


In [190]:
# Two variables pointint to same object have the same ID/memory location
a = [10,20,30]
b = a
print(id(a),id(b))

1935782049992 1935782049992


In [191]:
# Comparing variable storage in Python (reference type) vs C (value type)

"""
Storage in C:
int x = 10
x.loc = 00xU556
x.value = 10
"""

"""
Storage in Python:
x = 10
x -> object (10) # x references/points to this object (object has type/memory/ref)
obj.type = integer
obj.value = 10
obj.reference = 1
"""

### Key takeaway
# C creates a box for every label/variable
# Py puts different labels on the same box

'\nStorage in Python:\nx = 10\nx -> object (10) # x references/points to this object (object has type/memory/ref)\nobj.type = integer\nobj.value = 10\nobj.reference = 1\n'

In [192]:
# Adding two numerical lists together (same as append/union of two lists)
[1,2,3] + [4,5,'abcxyz']

[1, 2, 3, 4, 5, 'abcxyz']

In [193]:
# Unpacking a list (easy pythonic way)
a,b,c = [1,2,3]
print(a,b,c)

1 2 3


### Tuple (Immutable Object)

In [194]:
# A tuple always starts and ends with the round brackets ()
int_tuple = (1,2,3)
print(type(int_tuple))
int_tuple

<class 'tuple'>


(1, 2, 3)

In [195]:
# Accessing elements of a tuple (similar to a list)
int_tuple

(1, 2, 3)

### Dictionary

In [196]:
# Dictionary is like an address book, in Python it is specified by a key:value
dictionary = {'student':['student1','student2'],"id":('id1','id2','id3'),"workshop_grade":['A','A-','A+']}
dictionary

{'student': ['student1', 'student2'],
 'id': ('id1', 'id2', 'id3'),
 'workshop_grade': ['A', 'A-', 'A+']}

In [197]:
# Printing the keys
dictionary.keys()

dict_keys(['student', 'id', 'workshop_grade'])

In [198]:
# Note how the IDs are a tuple and student names/grades are a list
dictionary.values()

dict_values([['student1', 'student2'], ('id1', 'id2', 'id3'), ['A', 'A-', 'A+']])

In [199]:
# Printing the specific values of a key
dictionary['workshop_grade']

['A', 'A-', 'A+']

In [200]:
# Prints keys and values of a dictionary
dictionary.items()

dict_items([('student', ['student1', 'student2']), ('id', ('id1', 'id2', 'id3')), ('workshop_grade', ['A', 'A-', 'A+'])])

# NumPy (Numerical Python)

In [201]:
import numpy
import numpy as np # alias of numpy is np

### Creating a NumPy array

In [202]:
# Creating a numpy array from a list
my_array = np.array([1.,2,3])
type(my_array)
#my_array

numpy.ndarray

In [203]:
# Accessing what the function does using a "?"
np.linspace?

In [204]:
# Creating an array using linspace (returns evenly spaced numbers between two intervals)
my_array = np.linspace(start = 0,stop = 10,num = 11)
my_array

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [205]:
np.arange?

In [206]:
# Creating an array using arange (returns array with start, stop-step and length of array ~ (stop-start)//step)
my_array = np.arange(start = 0,stop = 10,step = 3)
my_array

array([0, 3, 6, 9])

In [207]:
# Combining multiple data types into Numpy array - observe what happens in the output
my_array = np.array(['abc',2,True])
my_array

array(['abc', '2', 'True'], dtype='<U4')

In [208]:
# Other ways of creating arrays
np.zeros(10) 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### NumPy Matrix

In [209]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [210]:
# Reshaping a regular array into a matrix
my_array = np.linspace(0,10,12)
my_matrix = my_array.reshape(4,3) # 4 rows, 3 columns
my_matrix

array([[ 0.        ,  0.90909091,  1.81818182],
       [ 2.72727273,  3.63636364,  4.54545455],
       [ 5.45454545,  6.36363636,  7.27272727],
       [ 8.18181818,  9.09090909, 10.        ]])

In [211]:
# A numpy matrix is essentially a stack of numpy arrays 
my_matrix[2]

# Accessing a row/column/cell by [row,column]
#my_matrix[1,1]

array([5.45454545, 6.36363636, 7.27272727])

In [212]:
# Creating a numpy matrix of zeros
my_matrix = np.zeros((5,5))
type(my_matrix)

numpy.ndarray

In [213]:
# You can also create a matrix using numpy's matrix function (soon to be deprecated)
new_matrix = np.matrix([[1,2,3],[4,5,6]])
print(new_matrix)
#print(dir(new_matrix))
#print(dir(my_matrix))

[[1 2 3]
 [4 5 6]]


In [214]:
# Going beyond the 2-dimensional arrays
type(np.linspace(0,10,16).reshape(2,2,2,2))

numpy.ndarray

### Selection and Broadcasting

In [215]:
# Selecting range of items
my_array = np.linspace(0,10,101)
my_array[90:92]
my_array

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [216]:
# Selecting specific items
my_array[[10,15,20]] # Passing a list works

array([1. , 1.5, 2. ])

In [217]:
# Selecting even cells [startAt:endBefore:skip]
my_array[::3]

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3. , 3.3, 3.6,
       3.9, 4.2, 4.5, 4.8, 5.1, 5.4, 5.7, 6. , 6.3, 6.6, 6.9, 7.2, 7.5,
       7.8, 8.1, 8.4, 8.7, 9. , 9.3, 9.6, 9.9])

In [218]:
# Broadcasting
my_array[90:] = 100
my_array

array([  0. ,   0.1,   0.2,   0.3,   0.4,   0.5,   0.6,   0.7,   0.8,
         0.9,   1. ,   1.1,   1.2,   1.3,   1.4,   1.5,   1.6,   1.7,
         1.8,   1.9,   2. ,   2.1,   2.2,   2.3,   2.4,   2.5,   2.6,
         2.7,   2.8,   2.9,   3. ,   3.1,   3.2,   3.3,   3.4,   3.5,
         3.6,   3.7,   3.8,   3.9,   4. ,   4.1,   4.2,   4.3,   4.4,
         4.5,   4.6,   4.7,   4.8,   4.9,   5. ,   5.1,   5.2,   5.3,
         5.4,   5.5,   5.6,   5.7,   5.8,   5.9,   6. ,   6.1,   6.2,
         6.3,   6.4,   6.5,   6.6,   6.7,   6.8,   6.9,   7. ,   7.1,
         7.2,   7.3,   7.4,   7.5,   7.6,   7.7,   7.8,   7.9,   8. ,
         8.1,   8.2,   8.3,   8.4,   8.5,   8.6,   8.7,   8.8,   8.9,
       100. , 100. , 100. , 100. , 100. , 100. , 100. , 100. , 100. ,
       100. , 100. ])

In [219]:
# Selecting items in a matrix
my_matrix = np.linspace(0,10,9).reshape(3,3)
my_matrix

array([[ 0.  ,  1.25,  2.5 ],
       [ 3.75,  5.  ,  6.25],
       [ 7.5 ,  8.75, 10.  ]])

In [220]:
# Syntax for selection matrix[row,column]
my_matrix[0,1]

1.25

In [221]:
# A new way of selecting items
my_array = np.linspace(-1,1,3)
#print(my_array)
my_array>0
bool_array = [True,True,False]
my_array[bool_array]
#print(my_array)
#print(my_array>0)
#my_array[my_array>0]

array([-1.,  0.])

In [222]:
# A new way of selecting items
my_matrix = np.linspace(0,10,9).reshape(3,3)
print(my_matrix)
my_matrix>5

[[ 0.    1.25  2.5 ]
 [ 3.75  5.    6.25]
 [ 7.5   8.75 10.  ]]


array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

### NumPy Array Operations

In [223]:
# Easy way to find all functions of NumPy
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [224]:
# This works in Numpy arrays (unlike lists)
#[1,2]+[3,4]
np.array([1,2,3])+np.array([4,5,6])

array([5, 7, 9])

In [225]:
# Max value of numpy array
my_array = np.linspace(-10,10,21)
print(my_array)
my_array.max()

[-10.  -9.  -8.  -7.  -6.  -5.  -4.  -3.  -2.  -1.   0.   1.   2.   3.
   4.   5.   6.   7.   8.   9.  10.]


10.0

In [226]:
# Argmax value of numpy array (location at which the max occurs)
my_array = np.linspace(-10,10,21)
my_array.argmax()

20

In [227]:
# Alternate ways to compute max, argmax, sum, cumsum
my_array.sum() # We can do this because the numpy array has this attribute

0.0

In [228]:
# Exponentials (array.exp() can not be used)
np.exp(my_array)

array([4.53999298e-05, 1.23409804e-04, 3.35462628e-04, 9.11881966e-04,
       2.47875218e-03, 6.73794700e-03, 1.83156389e-02, 4.97870684e-02,
       1.35335283e-01, 3.67879441e-01, 1.00000000e+00, 2.71828183e+00,
       7.38905610e+00, 2.00855369e+01, 5.45981500e+01, 1.48413159e+02,
       4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
       2.20264658e+04])

In [229]:
# Warning of log
np.mean(my_array)

0.0

In [230]:
# Stacking numpy arrays
my_array1 = np.array([1,2,3])
my_array2 = np.array([4,5,6])
print(my_array1,my_array2)
print(np.hstack((my_array1,my_array2)))

[1 2 3] [4 5 6]
[1 2 3 4 5 6]


In [231]:
# Vertically stacking arrays
print(np.vstack((my_array1,my_array2)))

[[1 2 3]
 [4 5 6]]


In [232]:
# Sorting your array
my_array = np.linspace(0,10,10)
my_array[0] = 100
#print(my_array)
#my_array = my_array.sort()
#my_array
my_array.sort()
my_array

array([  1.11111111,   2.22222222,   3.33333333,   4.44444444,
         5.55555556,   6.66666667,   7.77777778,   8.88888889,
        10.        , 100.        ])

In [233]:
# Numpy Sort has no inbuilt functionality to give descending order
# Trick to reverse the order of numpy array
my_array[::-1] 

array([100.        ,  10.        ,   8.88888889,   7.77777778,
         6.66666667,   5.55555556,   4.44444444,   3.33333333,
         2.22222222,   1.11111111])

### NumPy Matrix Operations

In [234]:
# Matrix addition (Creating two identical shape matrices)
my_matrix1 = np.linspace(0,10,20).reshape(4,5)
my_matrix2 = np.linspace(30,40,20).reshape(4,5)
my_matrix1

array([[ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316],
       [ 2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211],
       [ 5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105],
       [ 7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ]])

In [235]:
my_matrix2

array([[30.        , 30.52631579, 31.05263158, 31.57894737, 32.10526316],
       [32.63157895, 33.15789474, 33.68421053, 34.21052632, 34.73684211],
       [35.26315789, 35.78947368, 36.31578947, 36.84210526, 37.36842105],
       [37.89473684, 38.42105263, 38.94736842, 39.47368421, 40.        ]])

In [236]:
# Matrix addition
my_matrix1+my_matrix2

array([[30.        , 31.05263158, 32.10526316, 33.15789474, 34.21052632],
       [35.26315789, 36.31578947, 37.36842105, 38.42105263, 39.47368421],
       [40.52631579, 41.57894737, 42.63157895, 43.68421053, 44.73684211],
       [45.78947368, 46.84210526, 47.89473684, 48.94736842, 50.        ]])

In [237]:
# Adding constant
my_matrix1+100

array([[100.        , 100.52631579, 101.05263158, 101.57894737,
        102.10526316],
       [102.63157895, 103.15789474, 103.68421053, 104.21052632,
        104.73684211],
       [105.26315789, 105.78947368, 106.31578947, 106.84210526,
        107.36842105],
       [107.89473684, 108.42105263, 108.94736842, 109.47368421,
        110.        ]])

In [238]:
# Matrix multiplication two 4x5 matrices (transposing matrices)
np.matmul(my_matrix1.T,my_matrix2) 

array([[570.63711911, 578.94736842, 587.25761773, 595.56786704,
        603.87811634],
       [642.10526316, 651.52354571, 660.94182825, 670.3601108 ,
        679.77839335],
       [713.5734072 , 724.09972299, 734.62603878, 745.15235457,
        755.67867036],
       [785.04155125, 796.67590028, 808.31024931, 819.94459834,
        831.57894737],
       [856.50969529, 869.25207756, 881.99445983, 894.73684211,
        907.47922438]])

In [239]:
# What happens when we compare a matrix to a constant
mat = np.linspace(0,10,16).reshape(4,4)
print(mat)
mat>=5

[[ 0.          0.66666667  1.33333333  2.        ]
 [ 2.66666667  3.33333333  4.          4.66666667]
 [ 5.33333333  6.          6.66666667  7.33333333]
 [ 8.          8.66666667  9.33333333 10.        ]]


array([[False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [240]:
# Identity matrix
identity_matrix = np.identity(10)
identity_matrix

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [241]:
# Diagonal of matrix
np.diag(identity_matrix)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [242]:
# The Linear Algebra library of NumPy (advanced operations)
np.linalg?

### Random Numbers

In [243]:
# Generating random numbers using Numpy's random function
np.random.rand?

In [244]:
# Creates an array of random numbers from [0,1) - uniform distribution
random_array = np.random.rand(10)
random_array

array([0.04096174, 0.75922396, 0.71580304, 0.86629091, 0.12420951,
       0.93781273, 0.67303369, 0.15417793, 0.61904207, 0.97833321])

In [245]:
# Generating a random matrix (Uniform distribution)
random_matrix = np.random.rand(5,5)
random_matrix

array([[0.02455181, 0.41277876, 0.51650122, 0.40860528, 0.36267558],
       [0.98369199, 0.38759251, 0.78419648, 0.07073968, 0.48251148],
       [0.64864541, 0.31658254, 0.20890233, 0.39816025, 0.36508758],
       [0.91875354, 0.06101483, 0.26056945, 0.12165441, 0.8626136 ],
       [0.05188944, 0.66166087, 0.12447897, 0.00963596, 0.31002604]])

In [246]:
# Generating random integers
np.random.randint(low=0,high=10,size=100)

array([0, 9, 8, 7, 6, 0, 8, 8, 9, 1, 8, 9, 5, 7, 7, 7, 0, 4, 0, 0, 4, 9,
       6, 0, 6, 6, 1, 8, 6, 2, 1, 9, 9, 5, 8, 1, 5, 9, 4, 3, 2, 8, 7, 4,
       0, 7, 9, 2, 8, 8, 6, 8, 3, 8, 0, 1, 2, 9, 2, 7, 0, 3, 8, 7, 4, 1,
       8, 6, 4, 6, 4, 2, 9, 9, 4, 8, 9, 4, 0, 7, 7, 1, 0, 8, 6, 1, 2, 7,
       2, 8, 6, 5, 3, 3, 5, 7, 2, 1, 6, 0])

In [247]:
# Setting seed (very important - for future projects to ensure reproducible results)
np.random.seed(123)
np.random.rand(5)

array([0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897])

In [248]:
np.random.seed(123)
np.random.rand(5)

array([0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897])

In [249]:
np.linalg?

# Take Home Questions

To keep you thinking about Python

- Create a list([3,4,5,7,8]) and store it in variable "my_list". The list contains 5 elements. Write a program to interchange the first and second elements with the last and second last elements respectively. The new list will be [8,7,5,4,3]. 

- Create a dictionary with five stocks (any five stocks from S&P 500). The keys of the dictionary that you will have to populate are - Name, Company Sector, Price, Market Cap (USD Mn), and Price-Earnings Ratio. You should find such data on Yahoo Finance. The keys have to be strings. For example (https://finance.yahoo.com/quote/TSLA/).


- Using NumPy's arange and linspace, generate the same arrays between [0,10] and the array has size of 101 elements. Check if all the elements match.


- Generate 50 random numbers from [0,1) using np.random.rand function and calculate the mean, median, and variance.


- Now reshape the above array into a 10x5 matrix (10 rows and 5 columns). calculate the same statistics for each **column**.


- Generate 50 random numbers from [0,1). Split this array into two equal arrays of size 25 each. Now reshape the two new arrays into 5x5 matrices and multiply both of them. Calculate the determinant of the new matrix (check wiki if you don't know what it means). *Hint - you will find the determinant function part of the numpy linalg function (the linear algebra library)*